Api/urls.py
from django.urls import path
from Api import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'api_app'

urlpatterns = [
    path('blogs/posts/', views.PostApi.as_view(), name='post_api'),
    path('blogs/category/', views.CategoryApi.as_view(), name='category_api'),
    path('blogs/category/<id>/', views.SubCategoryApi.as_view(), name='sub_category_api'),
    path('blogs/category/<id>/<sub_id>/', views.FilterApi.as_view(), name='sub_filter_api'),
    path('blogs/comment/', views.AllCommentCreateViewApi.as_view(), name='all_comment_create_view_api'),
    path('blogs/comment/<post_id>/', views.CommentCreateViewApi.as_view(), name='comment_create_view_api'),
    path('blogs/filter/<category>/<text>/', views.BlogFilterApiView.as_view(), name='blog_filter_view_api'),
    path('blogs/filter/date/<category>/<text>/', views.BlogFilterDateApiView.as_view(),
         name='blog_filter_date_view_api'),

    path('bcs/package/<id>/', views.PackageListViewApi.as_view(), name='package_list_api'),
    path('bcs/subscription_service/<id>/', views.SubscriptionServiceApiView.as_view(), name='subscription_service'),

    path('bcs/services/<cat>/', views.ServiceListApiView.as_view(), name='service_list_api'),
    path('bcs/sub_service/<id>/', views.SubServiceApiView.as_view(), name='subservice_list_api'),
    path('bcs/sub_service_input/<id>/', views.SubServiceInputApiView.as_view(), name='subservice_input_list_api'),
    path('bcs/choice_field/<id>/', views.ChoiceApiView.as_view(), name='choice_field'),

    path('bcs/user_order/<id>/', views.UserSubServiceOrderApiView.as_view(), name='user_order'),  # Not

    path('bcs/team_permission/<id>/', views.TeamPermissionApiView.as_view(), name='team_permission'),

    path('bcs/bcs_admin_all_chart/', views.BCSAdminDashboardAllChartApiView.as_view(), name='bcs_admin_all_chart'),
    path('bcs/bcs_admin_year_chart/', views.BCSAdminDashboardYearChartApiView.as_view(), name='bcs_admin_year_chart'),
    path('bcs/bcs_admin_month_chart/', views.BCSAdminDashboardMonthChartApiView.as_view(),
         name='bcs_admin_month_chart'),
    path('bcs/bcs_admin_lastmonth_chart/', views.BCSAdminDashboardLastMonthChartApiView.as_view(),
         name='bcs_admin_lastmonth_chart'),
    path('bcs/bcs_admin_range_chart/', views.BCSAdminDashboardRangeChartApiView.as_view(),
         name='bcs_admin_chart_range'),
    

    path('pcs/pcs_admin_all_chart/', views.PCSAdminDashboardAllChartApiView.as_view(), name='pcs_admin_all_chart'),
    path('pcs/pcs_admin_year_chart/', views.PCSAdminDashboardYearChartApiView.as_view(), name='pcs_admin_year_chart'),
    path('pcs/pcs_admin_month_chart/', views.PCSAdminDashboardMonthChartApiView.as_view(),
         name='pcs_admin_month_chart'),
    path('pcs/pcs_admin_lastmonth_chart/', views.PCSAdminDashboardLastMonthChartApiView.as_view(),
         name='pcs_admin_lastmonth_chart'),
    path('pcs/pcs_admin_range_chart/', views.PCSAdminDashboardRangeChartApiView.as_view(),
         name='pcs_admin_range_chart'),

    path('main/main_admin_all_chart/', views.MainAdminDashboardAllChartApiView.as_view(), name='main_admin_all_chart'),
    path('main/main_admin_year_chart/', views.MainAdminDashboardYearChartApiView.as_view(),
         name='main_admin_year_chart'),
    path('main/main_admin_month_chart/', views.MainAdminDashboardMonthChartApiView.as_view(),
         name='main_admin_month_chart'),
    path('main/main_admin_lastmonth_chart/', views.MainAdminDashboardLastMonthChartApiView.as_view(),
         name='main_admin_lastmonth_chart'),
    path('main/main_admin_range_chart/', views.MainAdminDashboardRangeChartApiView.as_view(),
         name='main_admin_range_chart'),     

    path('bcs/bcs_subscriptions/<service>/', views.SubscriptionApiView.as_view(), name='bcs_subscriptions'),

    path('subscription_order/', views.SubscriptionOrderView.as_view(), name='subscription_order'),
    path('subscription_order_check/', views.SubscriptionPurchaseCheckApiView.as_view(), name='subscription_order_check'),
    path('pcs/course_order_check/', views.PCSCoursePurchaseCheckApiView.as_view(), name='course_order_check'),
    path('pcs/course_order/', views.PCSCoursePurchaseApiView.as_view(), name='course_order'),
    path('bcs/course_order_check/', views.BCSCoursePurchaseCheckApiView.as_view(), name='bcs_course_order_check'),
    path('bcs/course_order/', views.BCSCoursePurchaseApiView.as_view(), name='bcs_course_order'),

    path('bcs/bcs_course/<id>/', views.BCSCourseApiView.as_view(), name='bcs_course'),
    path('bcs/course_package/<id>/', views.BCSCoursePackageListViewApi.as_view(), name='course_package_list_api'),

    path('main/collective/', views.CollectiveApiView.as_view(), name='collective'),
    path('main/individual/', views.IndividualApiView.as_view(), name='individual'),
    path('main/business/', views.BusinessApiView.as_view(), name='business'),
    path('main/interest/', views.InterestApiView.as_view(), name='interest'),
    path('main/collective_notification/', views.CollectiveNotificationApiView.as_view(), name='collective_notification'),

    path('bcs/puchased_subscriptions/', views.SubscriptionTeamOrderApiView.as_view(), name='purchased_subscriptions'),
    path('bcs/puchased_course_subscriptions/', views.CourseSubscriptionTeamOrderApiView.as_view(),
         name='puchased_course_subscriptions'),
    path('bcs/subscription_team/', views.SubscriptionTeamAccessApiView.as_view(), name='subscription_team'),
    path('bcs/course_subscription_team/', views.CourseSubscriptionTeamAccessApiView.as_view(), name='course_subscription_team'),
    path('bcs/subscription_input/<id>/', views.SubscriptionInputApiView.as_view(), name='subscription_input'),

    path('bcs/team_input_info/<id>/', views.TeamInputInfoApiView.as_view(), name='team_input_info'),
]

MainTechforing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('BusinessSecurity.urls')),
    path('mysecurity/', include('PersonalSecurity.urls')),
    path('academy/', include('Academy.urls')),
    path('account/', include('Account.urls')),
    path('', include('Blog.urls')),
    path('api/', include('Api.urls')),
    path('accounts/', include('allauth.urls')),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'BusinessSecurity.views.error_404_handler'

BusinessSecurity/forms.py
from django import forms
from BusinessSecurity import models
from Academy.models import Course, duration, Section, Content, PackageFeatures, CoursePackage, CoursePurchase
from django.db.models import Q
from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import PhoneNumberPrefixWidget
from django.utils import timezone, dateformat


class AddServiceCategoryForm(forms.ModelForm):
    class Meta:
        model = models.ServiceCategory
        # fields = '__all__'
        exclude = ['category_choice', ]


class AddServiceForm(forms.ModelForm):
    category = forms.ModelChoiceField(widget=forms.Select(attrs={'class': 'form-select'}),
                                      queryset=models.ServiceCategory.objects.filter(category_choice='bcs'))

    # assign_to = forms.ModelChoiceField(widget=forms.SelectMultiple(attrs={'class': 'form-select js-example-basic-multiple'}), queryset=models.User.objects.filter(is_sales=True))

    # service_icon = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control'}))

    class Meta:
        model = models.Service
        fields = ['category', 'service_icon', 'service_title', 'short_description', 'service_header', 'service_body',
                  'service_footer', ]


class AddSubscriptionServiceForm(forms.ModelForm):
    category = forms.ModelChoiceField(widget=forms.Select(attrs={'class': 'form-select'}),
                                      queryset=models.ServiceCategory.objects.filter(category_choice='bcs'))

    # assign_to = forms.ModelChoiceField(widget=forms.SelectMultiple(attrs={'class': 'form-select js-example-basic-multiple'}), queryset=models.User.objects.filter(is_sales=True))

    # service_icon = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control'}))

    class Meta:
        model = models.SubscriptionServices
        fields = ['category', 'service_icon', 'service_title', 'short_description', 'service_header', 'service_body',
                  'service_footer', ]


class AddForm(forms.ModelForm):
    class Meta:
        model = models.InputFields
        fields = '__all__'


class AddSubServiceForm(forms.ModelForm):
    service = forms.ModelChoiceField(
        queryset=models.Service.objects.filter(has_sub_service=True, category_choice='bcs'),
        widget=forms.Select(attrs={'class': 'form-select'}))

    class Meta:
        model = models.SubService
        fields = '__all__'
        exclude = ['total_customer', ]
        widgets = {
            'fields': forms.SelectMultiple(attrs={'class': 'form-select js-example-basic-multiple'})
        }


class AddSubscriptionFieldsForm(forms.ModelForm):
    # subscriptionservice = forms.ModelChoiceField(
    #     queryset=models.SubscriptionServices.objects.filter(category_choice='bcs'),
    #     widget=forms.Select(attrs={'class': 'form-select'}), required=False)

    class Meta:
        model = models.SubscriptionField
        fields = '__all__'
        widgets = {
            'fields': forms.SelectMultiple(attrs={'class': 'form-select js-example-basic-multiple'})
        }
        exclude = ['subscriptionservice']


class CreateBusinessForm(forms.ModelForm):
    position = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'Enter Your Designation'}))
    website = forms.URLField(widget=forms.URLInput(
        attrs={'pattern': "^(?:http(s)?:\/\/)?[\w.-]+(?:\.[\w\.-]+)+[\w\-\._~:/?#[\]@!\$&'\(\)\*\+,;=.]+$",
               'value': "https://"}))

    class Meta:
        model = models.Business
        fields = '__all__'
        exclude = ['unique_id', 'company_logo']

    def clean(self):
 
        # data from the form is fetched using super function
        super(CreateBusinessForm, self).clean()
         
        # extract the email field from the data
        email = self.cleaned_data.get('email')
        email_set={'gmail','protonmail','hotmail','yahoo','zoho','aim','aol','gmx','icloud','yandex'}
        if email.split('@')[1].split('.')[0].lower() in email_set:
              raise forms.ValidationError('The email need to be a bussinees email')

class AddPackageForm(forms.ModelForm):
    service_id = forms.ModelChoiceField(
        queryset=models.SubscriptionServices.objects.filter(category_choice='bcs'))

    class Meta:
        model = models.SubscriptionBasedPackage
        fields = '__all__'
        exclude = ['package_id', 'category_choice']


class AddPackageFeatureForm(forms.ModelForm):
    # service_id = forms.ModelChoiceField(queryset=models.Service.objects.filter(is_subscription_based=True))

    class Meta:
        model = models.SubscriptionFeatures
        fields = '__all__'


class AddIndividualPackageFeatureForm(forms.ModelForm):
    class Meta:
        model = models.SubscriptionFeatures
        fields = ['feature_name', 'feature']


class EventCreateForm(forms.ModelForm):
    date_time = forms.DateTimeField(input_formats=['%Y/%m/%d %H:%M'])

    # time_field = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'time'}),
    #                                  input_formats=['%H:%M', '%I:%M%p', '%I:%M %p'])

    class Meta:
        model = models.Events
        fields = '__all__'
        # exclude = ('event_image',)
# class EventPictureForm(forms.ModelForm):
#     profile_pic = forms.ImageField(widget=forms.FileInput)
#     class Meta:
#         model = models.Events
#         fields = ['event_image']

class OrderPriceForm(forms.ModelForm):
    class Meta:
        model = models.OrderPrice
        fields = ['initial_price', 'discount', 'processing_fee', 'tax', 'currency', 'payment_method'] #, 'invoice'
        widgets = {
            'discount': forms.NumberInput(attrs={'max': '100'}),
            'currency': forms.Select(attrs={'class': 'form-select'}),
            'payment_method': forms.Select(attrs={'class': 'form-select'}),
            'invoice': forms.FileInput(attrs={'class': 'form-control'})
        }


class QuotationForm(forms.ModelForm):
    class Meta:
        model = models.Quotation
        # fields = '__all__'
        exclude = ['category_choice', 'order', 'agreement']


class QuotationAgreementForm(forms.ModelForm):
    class Meta:
        model = models.QuotationAgreement
        exclude = ['quotation']


class OrderAssignForm(forms.ModelForm):
    staff = forms.ModelChoiceField(
        queryset=models.User.objects.filter(
            Q(is_staff=True, is_sales=True) | Q(is_superuser=True) | Q(is_staff=True, is_sales_head=True)),
        widget=forms.Select(attrs={'class': 'js-example-basic-single form-control form-select'}))

    class Meta:
        model = models.OrderStaff
        fields = ['staff', ]


class TicketCreateForm(forms.ModelForm):
    ticket_category = forms.Field(
        widget=forms.Select(attrs={'class': 'form-select'}))
    ticket_attachment = forms.FileField(widget=forms.FileInput(attrs={'accept': 'image/*,video/*,audio/*,.pdf,.csv'}),required=False)

    class Meta:
        model = models.Ticket
        fields = ['ticket_title', 'ticket_category', 'issue_category',
                  'ticket_description', 'ticket_attachment']
        # exclude = ['category_choice', 'ticket_status']


class TicketCommentForm(forms.ModelForm):
    class Meta:
        model = models.TicketComment
        fields = ['comment']


class BusinessLogoForm(forms.ModelForm):
    class Meta:
        model = models.Business
        fields = ['company_logo']


class BusinessInfoForm(forms.ModelForm):
    # industry_type = forms.Field(widget=forms.Select(attrs={'class': 'form-select'}))
    class Meta:
        model = models.Business
        exclude = ['company_logo', 'unique_id']
        widgets = {
            'industry_type': forms.Select(attrs={'class': 'form-select'})
        }


class AssignToServiceForm(forms.ModelForm):
    class Meta:
        model = models.ServiceAssigned
        fields = ['service']
        widgets = {
            'service': forms.SelectMultiple(attrs={'class': 'js-example-basic-multiple'})
        }


class NotificationForm(forms.ModelForm):
    # category_choice = forms.ChoiceField(label='Select Target Users', choices=models.category_choice)
    notification_time = forms.DateTimeField(input_formats=['%Y/%m/%d %H:%M'], widget=forms.TextInput(
        attrs={'value': dateformat.format(timezone.now(), 'Y/m/d H:i')}))

    class Meta:
        model = models.Notification
        fields = '__all__'
        exclude = ['is_read']

templates/admin_panel/mainTF/editForm.html
{% extends 'base/main_admin_base.html' %} {% load static %}
{% load crispy_forms_tags %}
{% load hosts %}
{% block title %} Events {% endblock title %} {% block headercss %}
    <link rel="stylesheet" href="{% static 'tfcss/admin_panel/mainTF/eventWebinar.css' %}"/>
    <link rel="stylesheet" href="https://cdn.datatables.net/rowreorder/1.2.8/css/rowReorder.dataTables.min.css"/>
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.9/css/responsive.dataTables.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>
{% endblock headercss %} {% block content %}

    <main>
        {% if support_edit %}
            <form action="" id="employeeAddForm" method="POST" class="d-flex flex-column">

                <label for="user" style="font-weight: 700; margin-top: 1rem;">Permission*</label>
                <select multiple required name="user_permission"
                        class="form-control form-select admin_type">
                    <option value="sales" {% if current_user.is_sales %}selected="selected"{% endif %}>Sales</option>
                    <option value="blogger" {% if current_user.is_blogger %}selected="selected"{% endif %}>Blogger</option>
                    <option value="bcs_head" {% if current_user.is_bcs_head %}selected="selected"{% endif %}>BCS Head</option>
                    <option value="pcs_head" {% if current_user.is_pcs_head %}selected="selected"{% endif %}>PCS Head</option>
                </select>

                {% csrf_token %}
                <button class="btn btn-primary" type="submit">Add Stuff</button>
            </form>
        {% else %}
            <form action="" method="POST" enctype="multipart/form-data">
                {{ form.media }}
                {{ form|crispy }}
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
                <button class="btn btn-primary" type="submit">Update</button>
            </form>
        {% endif %}

    </main>
{% endblock content %}
{% block customjs %}
    {% if support_edit %}
        <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
        <script>
            // In your Javascript (external .js resource or <script> tag)
            $(document).ready(function () {
                $('.admin_type').select2()
            });

        </script>
        <script>
            let services = `{{ form|crispy }}`;
            let initVal = $('.admin_type').val()[0];
            if (initVal !== 'sales') {
                $('.admin_type option[value="sales"]').prop('disabled', true);

                if (document.querySelector('.servicesList'))
                    document.querySelector('.servicesList').outerHTML = '';
            } else {
                $('.admin_type  option[value!="sales"]').prop('disabled', true);

                if (!document.querySelector('.servicesList')) {
                    document.querySelector('#employeeAddForm button[type="submit"]').insertAdjacentHTML('beforebegin', '<div class="servicesList">' + services + '</div>');
                    $('.js-example-basic-multiple').select2()
                }
            }

            $('.admin_type').on('select2:select', function (e) {
                let data = e.params.data;

                ($(this).select2('data')).forEach(item => {
                    if (item.id == 'sales') {
                        document.querySelectorAll('.select2-selection__rendered li').forEach(li => {
                            if (li.title != 'Sales')
                                li.outerHTML = '';
                        })
                    }
                })
                if (data.text !== 'Sales') {
                    $('.admin_type option[value="sales"]').prop('disabled', true);

                    if (document.querySelector('.servicesList'))
                        document.querySelector('.servicesList').outerHTML = '';
                } else {
                    $(this).val(null).trigger('change');
                    $(this).val('sales').trigger('change');
                    $('.admin_type  option[value!="sales"]').prop('disabled', true);


                    if (!document.querySelector('.servicesList')) {
                        document.querySelector('#employeeAddForm button[type="submit"]').insertAdjacentHTML('beforebegin', '<div class="servicesList">' + services + '</div>');
                        $('.js-example-basic-multiple').select2()
                    }
                }
            });

            $('.admin_type').on('change', function (e) {
                if ($(this).find('option:selected').length === 0) {
                    $('.admin_type  option').prop('disabled', false);
                    if (document.querySelector('.servicesList'))
                        document.querySelector('.servicesList').outerHTML = '';
                }
            });

        </script>
    {% endif %}
    <script src="{% static 'tfjs/admin_panel/mainTF/eventWebinar.js' %}"></script>
    <script src="https://cdn.datatables.net/rowreorder/1.2.8/js/dataTables.rowReorder.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.9/js/dataTables.responsive.min.js"></script>
{% endblock customjs %}

templates/admin_panel/mainTF/notification.html
{% extends 'base/main_admin_base.html' %}
{% load static %}
{% load hosts %}
{% load crispy_forms_tags %}
{% block title %} Notifications
{% endblock title %}
{% block headercss %}
    <link rel="stylesheet" href="{% static 'tfcss/admin_panel/mainTF/notification.css' %}"/>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>
    <style>
        #notification-table_filter {
            margin-bottom: 2rem;
            float: right;
            width: 60%;
        }

        #notification-table_filter label {
            padding: 0.5rem 1rem;
            width: 100%;
            border: 1px solid #707070;
        }

        #notification-table_length label {
            display: flex;
            align-items: center;
            gap: 1rem;
            width: 26%;
        }

        #notification-table_length .form-select {
            width: 200px;
        }

        #notification-table_filter input {
            display: inline !important;
            border-color: transparent;
            width: 90%;
            padding: 0 0.75rem;
        }

        @media (min-width: 1000px) {
            .notification-table {
                width: 1400x !important;
            }
        }
    </style>
{% endblock headercss %}
{% block content %}

    <main class="mb-5">
        <div class="container">
            <div class="row my-3">
                <h3 class="text-uppercase">Select Category</h3>
                <select name="notification_type" id="notification_type" class="form-select mb-3">
                    <option value="individual">Individual</option>
                    <option value="business">Business</option>
                    <option value="collective">Collective</option>
                    <option value="interest">Interest</option>
                    <option value="date_range">Date Range</option>
                </select>
                <form action="" method="POST">
                    {% csrf_token %}
                    <h3 class="text-uppercase">send Notification</h3>
                    {{ form.media }}
                    {{ form|crispy }}
                    <div class="">
                        <button name="instant-btn" class="btn btn-primary fw-bolder text-uppercase float-end sendBtn"
                                type="submit">
                            send
                        </button>
                    </div>
                </form>
            </div>
            {% comment %}
            <div class="row my-3">
                <h3 class="text-uppercase">auto Notification</h3>
                <hr class="my-4"/>
                <h5 class="text-uppercase mb-3">create notification</h5>
                <textarea name="send-notification" id="" cols="30" rows="10" placeholder="write here"
                          style="height:60px; width:95%; margin-inline-start: 1rem;" class="addNotification"></textarea>
                <span class="d-none text-danger addError fw-bolder">Notification cannot be empty!</span>
                <div class="row my-3">
                    <div class="col-md-3">
                        <select class="form-select" aria-label="Default select">
                            <option>Select target users</option>
                            <option value="">New User</option>
                            <option value="">New Subscribe User</option>
                        </select>
                    </div>
                    <div class="col-md-3">
                        <select class="form-select" aria-label="Default select">
                            <option>
                                Select target users by interest list
                            </option>
                            <option value="">Concierge Cybersecurity</option>
                            <option value="">Security Compliance</option>
                            <option value="">Training Program</option>
                        </select>
                    </div>
                    <div class="col-md-5 d-flex align-center">
                        <label for="notificationRange" class="notificationRange">Select Date & time: </label>
                        <input type="datetime-local" class="form-control" placeholder="Select a Date and Time"
                               id="notificationRange"/>
                    </div>
                    <div class="col-md-1">
                        <button class="btn btn-primary text-uppercase float-end addBtn">
                            add
                        </button>
                    </div>
                </div>
            </div>
            {% endcomment %}
            <div class="row">
                <div class="col-md-12">
                    <table class="table notification-table" id="notification-table">
                        <thead class="text-center text-uppercase">
                        <tr>
                            <th>notification text</th>
                            <th>target user</th>
                            <th>time</th>      
                            <th>Action</th>             
                        </tr>
                        </thead>
                        <tbody>
                        {% for notification in notifications %}
                            <tr class="">
                                <td>{{ notification.notification|safe }}</td>
                                <td>{{ notification.category_choice|upper }}</td>
                                <td class="text-center">{{ notification.notification_time }}</td>
                                <td><a href="{% host_url 'main_admin_notification_delete' id=notification.id %}"
                                           class="btn trash">
                                            <i class="bi bi-trash-fill text-danger rounded-circle activites-icon"></i>
                                            Delete
                                        </a></td>
                                {% comment %} <td>{{ notification.notification_time }}</td> {% endcomment %}
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}
{% block customjs %}
    <script src="{% static 'tfjs/admin_panel/mainTF/notification.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        let categoryChoice = document.getElementById('id_category_choice');
        fetch(`${mainOrigin}/api/main/individual/`)
            .then(res => res.json())
            .then(data => {
                let categoryField = `<select id="id_category_choice" class="form-control" name="category_choice">`;
                data.response.forEach(option => {
                    categoryField += `<option value="${option.toLowerCase().replace(' ', '_')}">${option}</option>`;
                });
                categoryField += '</select>';
                categoryChoice.outerHTML = categoryField;

                $('#id_category_choice').select2();
            })

        document.getElementById('notification_type').addEventListener('change', e => {
            categoryChoice = document.getElementById('id_category_choice');
            if (e.target.value !== 'date_range') {
                fetch(`${mainOrigin}/api/main/${e.target.value}/`)
                    .then(res => res.json())
                    .then(data => {
                        if (document.querySelector('#daterange')) {
                            document.querySelector('#daterange').remove()
                            const daterangeLabel = document.querySelector("#div_id_category_choice label")
                            daterangeLabel.textContent = "Category choice*"
                            let categoryField = `<select id="id_category_choice" class="form-control" name="category_choice">`;
                            data.response.forEach(option => {
                                categoryField += `<option value="${option.toLowerCase()}">${option}</option>`;
                            });
                            categoryField += '</select>';
                            categoryChoice.outerHTML = categoryField;

                            $('#id_category_choice').select2();
                        } else {
                            let categoryField = `<select id="id_category_choice" class="form-control" name="category_choice">`;
                            data.response.forEach(option => {
                                categoryField += `<option value="${option.toLowerCase()}">${option}</option>`;
                            });
                            categoryField += '</select>';
                            categoryChoice.outerHTML = categoryField;

                            $('#id_category_choice').select2();
                        }

                    })
            } else {
                document.querySelector('.select2').remove()
                const daterange = document.querySelector("#div_id_category_choice")
                const daterangeLabel = document.querySelector("#div_id_category_choice label")
                daterangeLabel.textContent = "Select a Date range*"
                const dateInput = document.createElement("input")
                dateInput.setAttribute("type", "text")
                dateInput.setAttribute("name", "datetimes")
                dateInput.setAttribute("id", "daterange")
                dateInput.setAttribute("class", "form-select")
                dateInput.setAttribute("name", "date_range")
                daterange.appendChild(dateInput)
                $('#daterange').daterangepicker({
                    opens: 'right'
                }, function (start, end, label) {
                    console.log("A new date selection was made: " + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD'));
                });
            }
        });
    </script>
    <script>
        $(function () {
            $("#id_notification_time").datetimepicker();
        });
    </script>
{% endblock customjs %}