Api/urls.py
from django.urls import path
from Api import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'api_app'

urlpatterns = [
    path('blogs/posts/', views.PostApi.as_view(), name='post_api'),
    path('blogs/category/', views.CategoryApi.as_view(), name='category_api'),
    path('blogs/category/<id>/', views.SubCategoryApi.as_view(), name='sub_category_api'),
    path('blogs/category/<id>/<sub_id>/', views.FilterApi.as_view(), name='sub_filter_api'),
    path('blogs/comment/', views.AllCommentCreateViewApi.as_view(), name='all_comment_create_view_api'),
    path('blogs/comment/<post_id>/', views.CommentCreateViewApi.as_view(), name='comment_create_view_api'),
    path('blogs/filter/<category>/<text>/', views.BlogFilterApiView.as_view(), name='blog_filter_view_api'),
    path('blogs/filter/date/<category>/<text>/', views.BlogFilterDateApiView.as_view(),
         name='blog_filter_date_view_api'),

    path('bcs/package/<id>/', views.PackageListViewApi.as_view(), name='package_list_api'),
    path('bcs/subscription_service/<id>/', views.SubscriptionServiceApiView.as_view(), name='subscription_service'),

    path('bcs/services/<cat>/', views.ServiceListApiView.as_view(), name='service_list_api'),
    path('bcs/sub_service/<id>/', views.SubServiceApiView.as_view(), name='subservice_list_api'),
    path('bcs/sub_service_input/<id>/', views.SubServiceInputApiView.as_view(), name='subservice_input_list_api'),
    path('bcs/choice_field/<id>/', views.ChoiceApiView.as_view(), name='choice_field'),

    path('bcs/user_order/<id>/', views.UserSubServiceOrderApiView.as_view(), name='user_order'),  # Not

    path('bcs/team_permission/<id>/', views.TeamPermissionApiView.as_view(), name='team_permission'),

    path('bcs/bcs_admin_all_chart/', views.BCSAdminDashboardAllChartApiView.as_view(), name='bcs_admin_all_chart'),
    path('bcs/bcs_admin_year_chart/', views.BCSAdminDashboardYearChartApiView.as_view(), name='bcs_admin_year_chart'),
    path('bcs/bcs_admin_month_chart/', views.BCSAdminDashboardMonthChartApiView.as_view(),
         name='bcs_admin_month_chart'),
    path('bcs/bcs_admin_lastmonth_chart/', views.BCSAdminDashboardLastMonthChartApiView.as_view(),
         name='bcs_admin_lastmonth_chart'),
    path('bcs/bcs_admin_range_chart/', views.BCSAdminDashboardRangeChartApiView.as_view(),
         name='bcs_admin_chart_range'),
    

    path('pcs/pcs_admin_all_chart/', views.PCSAdminDashboardAllChartApiView.as_view(), name='pcs_admin_all_chart'),
    path('pcs/pcs_admin_year_chart/', views.PCSAdminDashboardYearChartApiView.as_view(), name='pcs_admin_year_chart'),
    path('pcs/pcs_admin_month_chart/', views.PCSAdminDashboardMonthChartApiView.as_view(),
         name='pcs_admin_month_chart'),
    path('pcs/pcs_admin_lastmonth_chart/', views.PCSAdminDashboardLastMonthChartApiView.as_view(),
         name='pcs_admin_lastmonth_chart'),
    path('pcs/pcs_admin_range_chart/', views.PCSAdminDashboardRangeChartApiView.as_view(),
         name='pcs_admin_range_chart'),

    path('main/main_admin_all_chart/', views.MainAdminDashboardAllChartApiView.as_view(), name='main_admin_all_chart'),
    path('main/main_admin_year_chart/', views.MainAdminDashboardYearChartApiView.as_view(),
         name='main_admin_year_chart'),
    path('main/main_admin_month_chart/', views.MainAdminDashboardMonthChartApiView.as_view(),
         name='main_admin_month_chart'),
    path('main/main_admin_lastmonth_chart/', views.MainAdminDashboardLastMonthChartApiView.as_view(),
         name='main_admin_lastmonth_chart'),
    path('main/main_admin_range_chart/', views.MainAdminDashboardRangeChartApiView.as_view(),
         name='main_admin_range_chart'),     

    path('bcs/bcs_subscriptions/<service>/', views.SubscriptionApiView.as_view(), name='bcs_subscriptions'),

    path('subscription_order/', views.SubscriptionOrderView.as_view(), name='subscription_order'),
    path('subscription_order_check/', views.SubscriptionPurchaseCheckApiView.as_view(), name='subscription_order_check'),
    path('pcs/course_order_check/', views.PCSCoursePurchaseCheckApiView.as_view(), name='course_order_check'),
    path('pcs/course_order/', views.PCSCoursePurchaseApiView.as_view(), name='course_order'),
    path('bcs/course_order_check/', views.BCSCoursePurchaseCheckApiView.as_view(), name='bcs_course_order_check'),
    path('bcs/course_order/', views.BCSCoursePurchaseApiView.as_view(), name='bcs_course_order'),

    path('bcs/bcs_course/<id>/', views.BCSCourseApiView.as_view(), name='bcs_course'),
    path('bcs/course_package/<id>/', views.BCSCoursePackageListViewApi.as_view(), name='course_package_list_api'),

    path('main/collective/', views.CollectiveApiView.as_view(), name='collective'),
    path('main/individual/', views.IndividualApiView.as_view(), name='individual'),
    path('main/business/', views.BusinessApiView.as_view(), name='business'),
    path('main/interest/', views.InterestApiView.as_view(), name='interest'),
    path('main/collective_notification/', views.CollectiveNotificationApiView.as_view(), name='collective_notification'),

    path('bcs/puchased_subscriptions/', views.SubscriptionTeamOrderApiView.as_view(), name='purchased_subscriptions'),
    path('bcs/puchased_course_subscriptions/', views.CourseSubscriptionTeamOrderApiView.as_view(),
         name='puchased_course_subscriptions'),
    path('bcs/subscription_team/', views.SubscriptionTeamAccessApiView.as_view(), name='subscription_team'),
    path('bcs/course_subscription_team/', views.CourseSubscriptionTeamAccessApiView.as_view(), name='course_subscription_team'),
    path('bcs/subscription_input/<id>/', views.SubscriptionInputApiView.as_view(), name='subscription_input'),

    path('bcs/team_input_info/<id>/', views.TeamInputInfoApiView.as_view(), name='team_input_info'),
]

Blog/urls.py
from django.urls import path, include
from Blog import views

urlpatterns = [
    path('blog/', views.indexView, name='index'),

    path('tinymce/', include('tinymce.urls')),
    path('category/', views.categoryView, name='category'),
#     path('category/<name>/', views.categoryView, name='category'),
    path('cybersecurity-<str:name>/', views.categoryView, name='cybersecurity'), # Changed the path for new url
    path('category/<str:name1>/<str:name2>/',
         views.category_detailView, name='category_detail'),
    path('category/<str:name1>/<str:name2>/<str:name3>/',
         views.category_detailFilterView, name='category_detail_filter'),
    path('articles/', views.postView, name='articles'),
    path('articles/<slug:name>/', views.postView, name='articles'),
    path('case_studies/', views.postView, name='case_studies'),
    path('case_studies/<slug:name>/', views.postView, name='case_studies'),
    path('podcast/', views.postView, name='podcast'),
    path('podcast/<slug:name>/', views.postView, name='podcast'),
    path('add_to_reading_list/', views.addToReadingListView,
         name='add_to_reading_list'),
    path('add_to_reading_list/<id>/',
         views.addToReadingListView, name='add_to_reading_list'),
    path('reading_list_post/', views.readingListPost,
         name='reading_list_post'),
    path('reading_list_post/<id>/', views.readingListPost,
         name='reading_list_post'),
    path('filter_post_keyword/<str:type>/<str:keyword>/',
         views.filter_post_keywordView, name='filter_post_keyword'),
    path('filter_post_date/<str:type>/<str:range>/',
         views.filter_post_dateView, name='filter_post_date'),
    path('related_posts/', views.relatedPostView, name='related_posts'),
    path('related_posts/<str:tag>/', views.relatedPostView, name='related_posts'),

    path('blog/dashboard/', views.adminDashboardView, name='admin_dashboard'),
    path('new/', views.adminNewPostView, name='admin_new'),
    path('blogform/', views.adminBlogFormView, name='admin_blog_form'),
    path('blogformedit/', views.adminBlogEditFormView,
         name='admin_blog_form_edit'),
    path('blogformedit/<int:id>', views.adminBlogEditFormView,
         name='admin_blog_form_edit'),
    path('delete_post/<int:id>', views.adminDeletePostView,
         name='admin_blog_delete'),
    path('delete_comment/<int:id>', views.adminDeleteCommentView,
         name='admin_comment_delete'),
    path('blogview/', views.adminBlogView, name='admin_blog_view'),
    path('categorylist/', views.adminCategoryListView, name='admin_category_list'),
    path('categoryview/', views.adminCategoryView, name='admin_category_view'),
    path('commentlist/', views.adminCommentListView, name='admin_comment_list'),
    path('commentview/', views.adminCommentView, name='admin_comment_view'),
    path('filteroptionlist/', views.adminFilterOptionListView,
         name='admin_filter_option'),
    path('filteroptionview/', views.adminFilterOptionView,
         name='admin_filter_view'),
    path('subcategorylist/', views.adminSubCategoryListView,
         name='admin_subcategory_list'),
    path('subcategoryview/', views.adminSubCategoryView,
         name='admin_subcategory_view'),

    path('category_delete/', views.categoryDeleteView, name='category_delete'),
    path('category_delete/<id>/', views.categoryDeleteView, name='category_delete'),
    path('subcategory_delete/', views.subCategoryDeleteView,
         name='subcategory_delete'),
    path('subcategory_delete/<id>/',
         views.subCategoryDeleteView, name='subcategory_delete'),
    path('filter_delete/', views.filterDeleteView, name='filter_delete'),
    path('filter_delete/<id>/', views.filterDeleteView, name='filter_delete'),
]

MainTechforing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('BusinessSecurity.urls')),
    path('mysecurity/', include('PersonalSecurity.urls')),
    path('academy/', include('Academy.urls')),
    path('account/', include('Account.urls')),
    path('', include('Blog.urls')),
    path('api/', include('Api.urls')),
    path('accounts/', include('allauth.urls')),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'BusinessSecurity.views.error_404_handler'

Blog/models.py
from django.db import models
from Account.models import User

from tinymce.models import HTMLField
import datetime

from django.dispatch import receiver
from django.db.models.signals import post_save

# Create your models here.
COMMENT_OPTIONS = (
    ('disabled', 'Disable Comments'),
    ('enabled', 'Enable Comments'),
)


class BlogCategory(models.Model):
    category = models.CharField(max_length=80)

    def __str__(self):
        return self.category

    @property
    def has_subcategories(self):
        if self.subcategory_category.all().count() > 0:
            return True
        else:
            return False

    class Meta:
        verbose_name_plural = 'Blog Categories'


class BlogSubCategory(models.Model):
    category = models.ManyToManyField(BlogCategory, related_name='subcategory_category', blank=True, null=True)
    sub_category = models.CharField(max_length=80)

    def __str__(self):
        return self.sub_category

    @property
    def has_filter(self):
        if self.filter_subcategory.all().count() > 0:
            return True
        else:
            return False

    class Meta:
        verbose_name_plural = 'Blog Sub Categories'


class FilterOption(models.Model):
    sub_category = models.ManyToManyField(BlogSubCategory, related_name='filter_subcategory', blank=True, null=True)
    filter_name = models.CharField(max_length=80)

    def __str__(self):
        return self.filter_name

    class Meta:
        verbose_name_plural = 'Blog Filter Option'


class Tags(models.Model):
    tag = models.CharField(max_length=100)

    def __str__(self):
        return self.tag

    class Meta:
        verbose_name_plural = 'Tags'


class Post(models.Model):
    author = models.ForeignKey(User, verbose_name='Author', on_delete=models.CASCADE)
    post_url = models.CharField(max_length=264, verbose_name='URL', unique=True)
    title = models.CharField(max_length=264, verbose_name='Add Title')
    category = models.ForeignKey(BlogCategory, on_delete=models.CASCADE, related_name='post_category')
    sub_categories = models.ForeignKey(BlogSubCategory, on_delete=models.CASCADE, related_name='post_sub_category',
                                       blank=True, null=True)
    filter_option = models.ForeignKey(FilterOption, on_delete=models.CASCADE, related_name='post_filter',
                                      blank=True, null=True)
    feature_image = models.ImageField(upload_to='blog/', verbose_name='Add Feature Image')
    short_description = models.TextField(verbose_name='Short Description', max_length=264)
    content = HTMLField(verbose_name='Post Content')
    reading_time = models.DurationField(default=datetime.timedelta(minutes=3))
    comment_option = models.CharField(choices=COMMENT_OPTIONS, default='disabled', max_length=100)
    tag = models.ManyToManyField(Tags, related_name='post_tags', verbose_name='Add Tags')
    date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    total_view = models.IntegerField(blank=True, default=0)

    def __str__(self):
        return self.title


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comment_user')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comment_post')
    comment = models.TextField(verbose_name='Comment', max_length=500)
    comment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.post.title}\'s comment'


reading_status = (
    ('read', 'Read'),
    ('unread', 'Unread'),
)


class ReadingList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reading_list_user')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='reading_list_post')
    added_on = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=255, choices=reading_status, default='unread')

    def __str__(self):
        return f'{self.user} - {self.post}'

# class BlogSubscription(models.Model):
#     full_name = models.CharField(max_length=255)
#     email = models.EmailField(unique=True)
#
#     def __str__(self):
#         return f'{self.full_name} - {self.email}'


# @receiver(post_save, sender=Post)
# def send_email(sender, instance, created, *args, **kwargs):
#     if created:
#         print(BlogSubscription.objects.all())

Blog/forms.py
from django import forms
from django.forms import widgets
from Blog import models


class PostForm(forms.ModelForm):
    # feature_image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control'}))
    comment_option = forms.ChoiceField(choices=models.COMMENT_OPTIONS,
                                       widget=forms.Select(attrs={'class': 'form-select'}))

    # post_url = forms.CharField(widget=forms.TextInput(
    #     attrs={'pattern': '([a-zA-Z0-9]|[-]|[_])'}))

    class Meta:
        model = models.Post
        fields = ['post_url', 'title', 'feature_image', 'short_description', 'content',
                  'comment_option', ]


class CategoryForm(forms.ModelForm):
    class Meta:
        model = models.BlogCategory
        fields = '__all__'


class SubCategoryForm(forms.ModelForm):
    class Meta:
        model = models.BlogSubCategory
        fields = '__all__'


class FilterOptionForm(forms.ModelForm):
    class Meta:
        model = models.FilterOption
        fields = '__all__'


# class BlogSubscriptionForm(forms.ModelForm):
#     class Meta:
#         model = models.BlogSubscription
#         fields = '__all__'
#         widgets = {
#             'full_name': forms.TextInput(attrs={'placeholder': 'Enter Your Name'}),
#             'email': forms.EmailInput(attrs={'placeholder': 'Enter Your Email'}),
#         }

templates/blog/admin.html
{% extends 'base/blog_base.html' %} {% load static %} {% load crispy_forms_tags %} {% block title %} Blogs
{% endblock title %} {% block headercss %}



<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">

<style>
    footer {
        display: none;
    }

    label {
        margin-block-start: 1.5rem;
        font-size: 1rem;
        font-weight: 700;
        text-transform: uppercase;
    }

    #id_short_description {
        height: 75px;
        resize: none;
    }

    .blogPost {
        margin-block: 1rem;
        padding-inline: 1.5rem;
    }
</style>

{% endblock headercss %} {% block content %}

<section class="w-75 container">
    <h3 class="fw-bold text-center my-5 border-bottom border-secondary">Add a new post</h3>
    <div id="content-main">
        <form enctype="multipart/form-data" method="POST" id="post_form">
            <label for="category">Category <span class="asteriskField">*</span></label>
            <select name="category" id="category" class="form-select" required>
                <option value="" disabled selected>Select a category</option>
            </select>
            <label for="subCategory" class="d-none">Sub Category <span class="asteriskField">*</span></label>
            <select name="subCategory" id="subCategory" class="form-select d-none">
                <option value="" disabled selected>Select a Sub category</option>
            </select>
            <label for="filterOption" class="d-none">Filter Option<span class="asteriskField">*</span></label>
            <select name="filterOption" id="filterOption" class="form-select d-none">
                <option value="" disabled selected>Select Filter Option</option>
            </select>
            {{ form.media }}
            {{ form|crispy }}
            {% csrf_token %}
            <label for="tagName" class="">Tag<span class="asteriskField">*</span></label>
            <select name="tagName" class="form-control js-example-tokenizer" id="tagName" multiple="multiple">
                <option value="" disabled>Select Tag</option>
                {% for tag in tag_list %}
                    <option>{{ tag }}</option>
                {% endfor %}
            </select>
            <button type="submit" class="btn btn-success blogPost">Post</button>
        </form>
    </div>

</section>

{% endblock content %} {% block customjs %}
<script id="django-admin-prepopulated-fields-constants" src="{% static '' %}admin/js/prepopulate_init.js"
    data-prepopulated-fields="[]" type="fd1fedd8f505b20d2a49a9ee-text/javascript">
</script>
<script>
    // CKEDITOR.replace('content');

    // // Enable local "abbr" plugin from /myplugins/abbr/ folder.
    // CKEDITOR.plugins.addExternal('abbr', '/myplugins/abbr/', 'plugin.js');

    // // extraPlugins needs to be set too.
    // CKEDITOR.replace('content', {
    //     extraPlugins: 'abbr'
    // });
    // CKEDITOR.replace('content', {
    //     skin: 'moonocolor,/myskins/moonocolor/'
    // });
    // CKEDITOR.replace('content', {
    //     customConfig: '/ckeditor_settings/config.js'
    // });
    $(document).ready(function () {
        // $('.js-example-basic-single').select2();
        $(".js-example-tokenizer").select2({
            tags: true,
            tokenSeparators: [',', ' ']
        })
    });
    const baseUrl = mainOrigin + "/"
    const blogCategory = document.getElementById("category")
    const blogSubCategory = document.getElementById("subCategory")
    const filterOption = document.getElementById("filterOption")
    window.addEventListener("load", () => {
        fetch(`${baseUrl}api/blogs/category/`)
            .then(response => response.json())
            .then(result => {
                result.map((item) => {
                    const newOption = document.createElement("option");
                    newOption.setAttribute("value", item.id)
                    newOption.setAttribute("has_subcategory", item.has_subcategory)
                    newOption.text = item.category
                    // console.log(newOption);
                    blogCategory.appendChild(newOption)
                })
            })
    })
    blogCategory.addEventListener("change", () => {
        const has_subcategory = blogCategory.options[blogCategory.selectedIndex].getAttribute("has_subcategory")
        blogSubCategory.innerHTML = `<option value="" disabled selected>Select a Sub category</option>`
        filterOption.previousElementSibling.classList.add("d-none")
        filterOption.classList.add("d-none")
        if (has_subcategory === "true") {
            blogSubCategory.previousElementSibling.classList.remove("d-none")
            blogSubCategory.classList.remove("d-none")
        } else if (has_subcategory === "false") {
            blogSubCategory.previousElementSibling.classList.add("d-none")
            blogSubCategory.classList.add("d-none")
        }
        fetch(`${baseUrl}api/blogs/category/${blogCategory.value}`)
            .then(response => response.json())
            .then(result => {
                result.map((item) => {
                    const newOption = document.createElement("option");
                    newOption.setAttribute("value", item.id)
                    newOption.setAttribute("has_filter", item.has_filter)
                    newOption.text = item.sub_category
                    blogSubCategory.appendChild(newOption)
                })
            })
    })
    blogSubCategory.addEventListener("change", () => {
        const has_filter = blogSubCategory.options[blogSubCategory.selectedIndex].getAttribute("has_filter")
        filterOption.innerHTML = `<option value="" disabled selected>Select a Sub category</option>`
        console.log(`${baseUrl}api/blogs/category/${blogCategory.value}/${blogSubCategory.value}`);
        if (has_filter === "true") {
            filterOption.previousElementSibling.classList.remove("d-none")
            filterOption.classList.remove("d-none")
            filterOption.setAttribute("required", true)
        } else if (has_filter === "false") {
            filterOption.previousElementSibling.classList.add("d-none")
            filterOption.classList.add("d-none")
            filterOption.removeAttribute("required")
        }
        fetch(`${baseUrl}api/blogs/category/${blogCategory.value}/${blogSubCategory.value}`)
            .then(response => response.json())
            .then(result => {
                // console.log(result);
                result.map((item) => {
                    // console.log(item.has_subcategory);
                    const newOption = document.createElement("option");
                    newOption.setAttribute("value", item.id)
                    newOption.text = item.filter_name
                    filterOption.appendChild(newOption)
                })
            })
    })
</script>
{% endblock customjs %}

templates/blog/related_posts.html
{% extends 'base/blog_base.html' %} {% load static %} {% load hosts %}{% load my_filter %} {% block title %} Related Posts {% endblock title %} {% block headercss %}
<link rel="stylesheet" href="{% static 'tfcss/blog/index.css' %}"> {% endblock headercss %} {% block content %}


<section class="my-4 p-2">
    <h4 class="fw-bold">Related Posts:</h4>

    {% for post in posts %}
    <div class="row mb-3 mx-0 bg-lightnavy">
        <div class="col-md-3 p-2 d-flex align-items-center">
            <img src="{{post.feature_image.url}}" class="img-fluid " alt="... ">
        </div>
        <div class="col-md-9 py-2 d-flex align-items-center">
            <div>
                <a href="{% host_url 'articles' host 'blog' %}{{post.post_url}}">
                    <h6 class="fw-bold">{{post.title}}</h6>
                </a>
                <p class="my-2 mb-0 fs-7 lh-sm">{{post.short_description}}</p>
                <div class="info-area mt-2">
                    <span class="p-0 me-3 text-green">
                        <i class="bi bi-calendar"></i>
                        {{post.date|date}}
                    </span>
                    <span class="p-0 me-3 text-green" title="Reading Time">
                        <i class="bi bi-stopwatch"></i>
                        {{post.reading_time}}
                    </span> {% if post.id not in reading_lists %}
                    <a href="{% host_url 'add_to_reading_list' host 'blog' %}{{ post.id }}" class="p-0 me-3 text-green" title="Add Reading List">
                        <i class="bi bi-plus-circle"></i> Add
                    </a>
                    {% else %}
                    <a href="{% host_url 'add_to_reading_list' host 'blog' %}{{ post.id }}" class="p-0 me-3 text-danger" title="Remove From Reading List">
                        <i class="bi bi-dash-circle"></i> Remove
                    </a>
                    {% endif %}

                </div>

            </div>
        </div>
    </div>
    {% endfor %}
</section>


{% endblock content %} {% block customjs %}

<script>
</script>
{% endblock customjs %}